### ISSUE TITLE
Loading Audio from URL

### ISSUE THREAD

**Issue by Lewiscowles1986** [Lewiscowles1986/webamp#15]
There needs to be a way to load (when online) from URL, which should also include the support of podcast URL's

* [ ] How to display to user the choice
* [ ] How/if to communicate to the user when offline
* [ ] How/if to work with a playlist with multiple items in case of podcast
* [ ] How to receive URL (themed UI seems the apex), JS prompt the minimum
