### ISSUE TITLE
Procedural code

### ISSUE THREAD

**Issue by Lewiscowles1986** [Lewiscowles1986/webamp#6]
Looks like this thing operates top->bottom and could have timing issues...

* [ ] extract functionality into single-purpose functions
* [ ] move to custom / alternative events & timers
* [ ] namespace player to prevent stepping on globals
